### PR TITLE
Remove unused var opts in _setup_var_data, avoid potential memory waste

### LINKED ISSUE #2928: Unused code or missing arg?
### Description

In the method below from meta_model_structured_comp.py, the dict `opts` is never used.  It's unclear to me whether it's just old code that should be removed or if it should be passed into `InterpND`.

### Example

```python
def _setup_var_data(self):
        """
        Instantiate surrogates for the output variables that use the default surrogate.
        """
        interp_method = self.options['method']

        opts = {}
        if 'interp_options' in self.options:
            opts = self.options['interp_options']
        for name, train_data in self.training_outputs.items():
            self.interps[name] = InterpND(method=interp_method,
                                          points=self.inputs, values=train_data,
                                          extrapolate=self.options['extrapolate'])

        if self.options['training_data_gradients']:
            self.grad_shape = tuple([self.options['vec_size']] + [i.size for i in self.inputs])

        super()._setup_var_data()
```

### OpenMDAO Version

3.26.1-dev

### Relevant environment information

_No response_

### PR DESCRIPTION
**Pull request by SaltySodaBunny**
### Summary
After checking the  _setup_var_data, I verified the opts dictionary is unused.
I remove this variable and the assignment line for this variable.

### Related Issues
- Resolves #2928

### CODE REVIEW

**Review by naylor-b — APPROVED** [review]

**Review by Kenneth-T-Moore — APPROVED** [review]

**Review by Kenneth-T-Moore — CHANGES_REQUESTED** [review]
Need to check something.

**Review by Kenneth-T-Moore — APPROVED** [review]
Ok, yeah. It looks like this part came over from the interpolating spline component, where it is needed for the bspline options. Interp_options isn't implemented here, but could be useful for setting a couple of things in Akima. It should come in as a feature with tests and docs in the future. For now, removing the extra code is the right thing to do.

**Comment by SaltySodaBunny** [comment]
Thank you for the code reviewing, it's my first time contributing on an open source project. Currently, I can't merge pull request because this commit is not signed. How can I solve this issue?

**Review by robfalck — CHANGES_REQUESTED** [review]
Could you please revert `units.py` to the same as the master version?

Those changes should be addressed in your other pull request but we shouldn't be introducing any of those changes in this one.

**Comment by swryan** [comment]
> Thank you for the code reviewing, it's my first time contributing on an open source project. Currently, I can't merge pull request because this commit is not signed. How can I solve this issue?

See this page:
https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by robfalck** [comment]
We can clean up the ops issue and save the units changes for later.

**Pull request closed without merging**
