### PR TITLE
Reconfigurable Model Execution - connection tests

### PR DESCRIPTION
**Pull request by onodip**
Added tests with "expected failure" for connections of a reconfigurable problem.

Based on the following Stackoverflow question:
https://stackoverflow.com/questions/53231118/how-to-update-connection-sizes-in-a-reconfigurable-model-in-openmdao-2-5-0

### CODE REVIEW

**Comment by onodip** [comment]
Appveyor fails with this case:
Environment: APPVEYOR_BUILD_WORKER_IMAGE=Ubuntu, PY=3.6, NUMPY=1.14, SCIPY=1.0.1, PETSc=3.9.1

The problem is with installin gthe wheel for PETSc, and it seems to be unrelated to the PR.

**Comment by kmarsteller** [comment]
(and the fail is after the test have passed. this is a known issue on Appveyor.)

**Comment by kmarsteller** [comment]
story created for this: https://www.pivotaltracker.com/story/show/161935661

**Comment by onodip** [comment]
> story created for this: https://www.pivotaltracker.com/story/show/161935661

Thank you!

**Pull request merged**
