### PR TITLE
add support for numpy min, max and diff in ExecComp

### PR DESCRIPTION
**Pull request by fzahle**
### Summary

Summary of PR.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

### CODE REVIEW

**Review by naylor-b — APPROVED** [review]

**Comment by fzahle** [comment]
we also use np.interp here and there, but adding this is more tricky since it doesn't pass the complex step test. Looking at using the `SplineComp` instead.

**Comment by JustinSGray** [comment]
wait ... min and max are not differentiable .... hrm....

**Comment by fzahle** [comment]
if you use complex step for derivatives, it should work since it will find the min/max along the real axis and return that along with the corresponding complex part.

**Comment by JustinSGray** [comment]
That is only mathematically valid if the location of the max-value in the array isn't changing. Will it work? probably for fairly well behaved functions. Anyway, its there now... so I guess we're stuck with it. So I can't object to adding the similar methods either. 

```
import numpy as np 

a = np.ones(4)*10

b = np.ones(4, dtype='complex')*10
b[0] += complex(0, 1e-50)

print(np.max(a))

print(np.max(b))

b[1] += 1e-10
print(np.max(b))
```

**Review by robfalck — APPROVED** [review]

**Pull request merged**
