### PR TITLE
XDSM fix XDSMjs gitmodule

### PR DESCRIPTION
**Pull request by onodip**
Added the .gitmodules file for XDSMjs missing from #813.

Also made the HTML file of XDSMjs embeddable, similarly as in `problem_viewer`.

### CODE REVIEW

**Comment by onodip** [comment]
@JustinSGray could you check, if it works now?

**Comment by onodip** [comment]
Now it fails with the following:
The command "eval git submodule update --init --recursive " failed 3 times.
The command "git submodule update --init --recursive" failed and exited with 1 during .

**Comment by relf** [comment]
Hi Peter. It seems that it points to an unpublished commit of XDSMjs.
<pre>
D:\rlafage\workspace\OpenMDAO [xdsm_mods = +0 ~1 -0 !]> git submodule update --init 
error: no such remote ref 85568b6277d01b94578c152cd9aede8e35f5b745
Fetched in submodule path 'openmdao/devtools/xdsm_viewer/XDSMjs', but it did not contain 85568b6277d01b94578c152cd9aede8
e35f5b745. Direct fetching of that commit failed.
D:\rlafage\workspace\OpenMDAO [xdsm_mods = +0 ~1 -0 !]>
</pre>

**Comment by JustinSGray** [comment]
although the CI is failing, i was able to build the XDSM via html now.

**Comment by onodip** [comment]
@relf in principle it should checkout the master, but I will try to fix it. It also might be, that OpenMDAO's `travis.yml` has to be edited.

The gitmodules file looked like this: 
```
[submodule "openmdao/devtools/xdsm_viewer/XDSMjs"]
	path = openmdao/devtools/xdsm_viewer/XDSMjs
	url = https://github.com/OneraHub/XDSMjs.git
```

**Comment by relf** [comment]
My guess is that you committed to XDSMjs locally. The hash 85568b6277d01b94578... does not exist in history of https://github.com/OneraHub/XDSMjs master branch. This is why travis complains:
<pre>
git submodule update --init --recursive
Submodule 'openmdao/devtools/xdsm_viewer/XDSMjs' (https://github.com/OneraHub/XDSMjs.git) registered for path 'openmdao/devtools/xdsm_viewer/XDSMjs'
Cloning into '/home/travis/build/OpenMDAO/OpenMDAO/openmdao/devtools/xdsm_viewer/XDSMjs'...
error: Server does not allow request for unadvertised object 85568b6277d01b94578c152cd9aede8e35f5b745
Fetched in submodule path 'openmdao/devtools/xdsm_viewer/XDSMjs', but it did not contain 85568b6277d01b94578c152cd9aede8e35f5b745. Direct fetching of that commit failed.
</pre>

Could you check the result of <code>git log</code> in your XDSMjs directory?

**Comment by onodip** [comment]
Thanks Rémi. It was indeed a commit on my own fork. Trying to get rid of it.

**Comment by Kenneth-T-Moore** [comment]
I submitted a pull request to your branch. It adds some cleanup of the files when the tests conclude, and also suppresses the output of pdflatex during execution.  You will need to pull down my mods to pyXDSM while my Pull Request is pending approval:

https://github.com/Kenneth-T-Moore/pyXDSM

**Comment by Kenneth-T-Moore** [comment]
So I'm happy with how the tests are running now. The only problem I had was with the XDSMjs submodule.

Submodules in git seem like a pretty elegant solution, and I expected it would work seamlessly, but the code didn't appear until I did a `git submodule init` followed by a `git submodule update`.  After that, the code appeared and tests pass. I'm a bit worried about adding the extra step to the normal install process for regular users as we integrate this.  I think it might be preferable to just include your modified XDSMjs implementation directly in the repo.

**Comment by onodip** [comment]
Alternatively `git clone --recursive http://github.com/OpenMDAO/OpenMDAO` should work. If it is not an option to change the installation instruction, then I will include directly in the repo.

**Comment by Kenneth-T-Moore** [comment]
There is also a local setting to always update when you pull, but let's just include the code in the repo, as it's safest.  Thanks, Peter.

**Comment by onodip** [comment]
@Kenneth-T-Moore okay, it is indeed more safe

**Pull request merged**
