### PR TITLE
Added ParOpt to pyoptsparse's option list

### PR DESCRIPTION
**Pull request by aaronyicongfu**
### Summary

Added ParOpt as an option so that it can be used through pyoptsparse driver

fyi, @gjkennedy

### Backwards incompatibilities

None

### New Dependencies

None

### CODE REVIEW

**Comment by gjkennedy** [comment]
I think this list of optimizers should ideally be pulled from pyOptSparse itself.

**Comment by Kenneth-T-Moore** [comment]
There is an issue up for this, in which Rob commented that pyoptsparse has temporarily disabled ParOpt as a choice in their most recent version at the time.  Has it been re-enabled in the current version? 

https://github.com/OpenMDAO/OpenMDAO/issues/1374

**Comment by gjkennedy** [comment]
We've fixed it. ParOpt should work again from pyOptSparse.

**Comment by Kenneth-T-Moore** [comment]
Herb has a Pull Request (#1581) that adds ParOpt and also adds a couple of tests, plus builds ParOpt for testing on our CI machines.

**Comment by swryan** [comment]
#1581 has been merged, which includes this functionality

**Pull request closed without merging**
