### PR TITLE
Refactored relevance and removed driver dependency for coloring.

### LINKED ISSUE #2690: Use relevance when computing objectives.
### Desired capability or behavior.

This is just a continuation of PR #2675.  Where that PR added relevance during calls to _linearize, this one will pass that same relevance information to calls to _solve_nonlinear during the computation of objectives by the driver.

### Associated POEM

_No response_

### LINKED ISSUE #2894: Consider relevance when computing approximations
### Task Description

OpenMDAO currently considers relevance for various linear computations, but currently doesn't for nonlinear ones that are performed while computing approximate derivatives.  Skipping execution of systems that are not dependent upon a given input could improve performance.

Another issue, #2690, also mentions adding relevance to solve_nonlinear, but in the context of a driver optimization.

### LINKED ISSUE #3037: Derivative computation is skipped if objective/constraints are defined while design vars aren't
### Description

When a model has an objective/constraint defined but no design variables, compute_totals skips the derivative computation, even when explicitly giving it "of" and "wrt" inputs. When the objective/constraints are removed, then it works.

This is probably not a very realistic use case, but could throw someone off if they're trying to check derivatives before the full optimization problem is defined, for example.

### Example

```import openmdao.api as om

class DummyComp(om.ExplicitComponent):
    def setup(self):
        self.add_input('a', 1.)
        self.add_output('b', 1.)
    def compute(self, inputs, outputs):
        outputs['b'] = 2. * inputs['a']
    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        if mode=='rev':
            if 'a' in d_inputs:
                if 'b' in d_outputs:
                    d_inputs['a'] += d_outputs['b'] * 2.

prob = om.Problem()
prob.model.add_subsystem('ivc', om.IndepVarComp(), promotes=['*'])
prob.model.ivc.add_output('a', 1.)
prob.model.add_subsystem('dummy', DummyComp(), promotes=['*'])

### when there's a objective/constraint but no design var, derivatives are zero because the derivative computation is skipped
#prob.model.add_design_var('a', lower=0., upper=2.)
#prob.model.add_constraint('b', lower=3.)
prob.model.add_objective('b')

prob.setup(mode='rev')
prob.run_model()
prob.check_totals(of='b', wrt='a')
```

### OpenMDAO Version

3.28.1-dev

### Relevant environment information

_No response_

### PR DESCRIPTION
**Pull request by naylor-b**
### Summary

Relevance was refactored, the the currently active relevance is determined by the current set of design variables and responses coming out of the model, or by 'of' and 'wrt' variables passed into Problem.compute_totals which don't have to be declared design variables or responses.

Design variables and responses are also no longer necessary to compute a total coloring.  This will lead to simplification of the SubModelComp (that work will be done in a future PR).

Relevance is now active while computing total derivatives using FD/CS.
Relevance is now active while computing objectives when using pyOptSparseDriver, but not ScipyOptimizeDriver, because activating relevance there caused several dymos test failures. This will be investigated and hopefully fixed in a later PR.

Relevance is not active under DirectSolvers or NewtonSolvers.

### Related Issues

- Resolves #2894
- Resolves #3037

### Backwards incompatibilities

The keys used in dictionaries returned by `compute_totals` will now contain 'user' specified names (either promoted names or aliases) instead of absolute names.  So they now match the names specified in add_design_var/add_constraint/add_objective, subject to promotion rules if they were declared below the top level.

The `rel_systems` arg was removed from some internal methods like `_solve_linear` and `_apply_linear`.  It was left in the `solve` method for linear solvers since that's public, but the arg is deprecated and does nothing now.

### New Dependencies

None

### CODE REVIEW

**Review by robfalck — APPROVED** [review]

**Comment by Asthelen** [comment]
I was testing out this PR with this parallel MPhys example: https://github.com/OpenMDAO/mphys/blob/main/examples/aerostructural/supersonic_panel/as_opt_parallel.py (with Tim's MPhys PR here: https://github.com/timryanb/mphys/tree/run_dir_update) and it gave me this error (when run on two processors):

`
Traceback (most recent call last):
  File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/mphys/examples/aerostructural/supersonic_panel/as_opt_parallel.py", line 172, in <module>
    prob.run_driver()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/problem.py", line 721, in run_driver
    driver.check_relevance()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/driver.py", line 971, in check_relevance
    raise RuntimeError(f"{self.msginfo}: Constraint(s) {bad_cons} do not depend on any "
RuntimeError: ScipyOptimizeDriver: Constraint(s) ['multipoint.aerostructural1.func_struct', 'multipoint.aerostructural1.C_L'] do not depend on any design variables. Please check your problem formulation.
Traceback (most recent call last):
  File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/mphys/examples/aerostructural/supersonic_panel/as_opt_parallel.py", line 172, in <module>
    prob.run_driver()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/problem.py", line 721, in run_driver
    driver.check_relevance()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/driver.py", line 971, in check_relevance
    raise RuntimeError(f"{self.msginfo}: Constraint(s) {bad_cons} do not depend on any "
RuntimeError: ScipyOptimizeDriver: Constraint(s) ['multipoint.aerostructural2.func_struct', 'multipoint.aerostructural2.C_L'] do not depend on any design variables. Please check your problem formulation.
`

I'm guessing the 1st rank doesn't think the aerostructural2 (which resides on rank 2) func_struct and CL constraints are relevant, and vice versa? A check_totals looked okay, however. For reference, that example should complete in 24 SLSQP iterations.

**Comment by naylor-b** [comment]
@Asthelen I'm testing a fix on my branch and I get this:
```
{'multipoint.aerostructural1.C_L': array([0.15]),
 'multipoint.aerostructural1.func_struct': array([1.00000024]),
 'multipoint.aerostructural2.C_L': array([0.45]),
 'multipoint.aerostructural2.func_struct': array([1.00000052])}

Objectives
{'multipoint.aerostructural1.mass': array([8.73298746e-05])}

Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.008732987463347464
            Iterations: 22
            Function evaluations: 24
            Gradient evaluations: 22
Optimization Complete
```
Does that look correct?

**Comment by Asthelen** [comment]
@naylor-b That does look correct, yeah. I'm guessing this is on your radar already, but I tried your latest push and got this error:

`
Traceback (most recent call last):
  File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/mphys/examples/aerostructural/supersonic_panel/as_opt_parallel.py", line 172, in <module>
    prob.run_driver()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/problem.py", line 744, in run_driver
    return driver.run()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/drivers/scipy_optimizer.py", line 288, in run
    model.run_solve_nonlinear()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/system.py", line 4422, in run_solve_nonlinear
    self._solve_nonlinear()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/core/group.py", line 3374, in _solve_nonlinear
    self._nonlinear_solver._solve_with_cache_check()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 26, in _solve_with_cache_check
    self.solve()  # don't use caching
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 45, in solve
    self._gs_iter()
  File "/hpnobackup2/asthelen/Codes/Repositories/OM_test/OpenMDAO/build/lib/openmdao/solvers/solver.py", line 852, in _gs_iter
    for subsys in system._relevant.filter(system._all_subsystem_iter()):
AttributeError: 'Relevance' object has no attribute 'filter'
`

That also happens with the simpler run.py MPhys example, which doesn't use parallel groups or coloring.

**Comment by naylor-b** [comment]
@Asthelen can you try it one more time to make sure everything works now?

**Comment by Asthelen** [comment]
Unfortunately, I seem to be getting the original error again? 

`RuntimeError: ScipyOptimizeDriver: Constraint(s) ['multipoint.aerostructural1.func_struct', 'multipoint.aerostructural1.C_L'] do not depend on any design variables. Please check your problem formulation.`

**Comment by naylor-b** [comment]
@Asthelen can you try this one more time?  Running your test case locally works for me now.

**Comment by Asthelen** [comment]
@naylor-b This does seem to work for me, but for some reason there appears to be an additional function call after the optimization completes. Is this supposed to happen?

The OM version I've been comparing to was last pushed to on Dec 5... haven't compared to the latest main branch, but I can do that if you think it's worthwhile.

**Comment by naylor-b** [comment]
@Asthelen there was a change to ScipyOptimizeDriver that calls model._solve_nonlinear at the end of the optimization.  This was done to fix an issue in dymos where it needed an irrelevant component to be executed at least once.  There will be a follow-on PR to this PR that unifies our linear and nonlinear relevance stuff that will get rid of the extra execution of ScipyOptimizeDriver.

**Comment by Asthelen** [comment]
@naylor-b I see--thanks for the explanation. That was the one possible issue I spotted with this latest commit.

**Pull request merged**
