### PR TITLE
Added deprecation column to options table

### LINKED ISSUE #2111: Update the show_options_table function to indicate which options are deprecated
### Summary of Issue

Currently, the `show_options_table` function doesn't give the user any indication if one of the options is deprecated. 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

Provide some indication if an option is deprecated. Maybe include the `deprecation` string from the option declaration.
 
### Example

The options for `openmdao.core.component.Component` has a deprecated option `distributed`.

### Environment

N/A

### PR DESCRIPTION
**Pull request by DKilkenny**
### Summary

Added deprecation column to options table. Only shows when there is a deprecation

### Related Issues

- Resolves #2111

### Backwards incompatibilities

None

### New Dependencies

None

### CODE REVIEW

**Comment by swryan** [comment]
needs a test or two? (for options with & without deprecation)

**Review by swryan — APPROVED** [review]

**Comment by Kenneth-T-Moore** [comment]
Can you provide some screenshots of this? (Or maybe share your screen during today's meeting.

**Comment by DKilkenny** [comment]
> Can you provide some screenshots of this? (Or maybe share your screen during today's meeting.

Here's a screenshot. We can talk about it at the meeting though if you have questions
Screen Shot 2021-06-23 at 9 23 36 AM

**Review by Kenneth-T-Moore — COMMENTED** [review]
Thanks, screenshot looks good.

**Review by Kenneth-T-Moore — APPROVED** [review]

**Pull request merged**
