### PR TITLE
In the Custom report example, make sure the entry point doesn't collide with our default names.

### PR DESCRIPTION
**Pull request by Kenneth-T-Moore**
### Summary

In the Custom report example, make sure the entry point doesn't collide with our default names.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

### CODE REVIEW

**Comment by swryan** [comment]
I would suggest that the doc probably needs to tell the user how to avoid name collisions as well...   I think we could tell them to do something like this to determine existing names:
```
from importlib.metadata import entry_points
eps = entry_points(group='openmdao_reports')
print([ep.name for ep in eps])
```

**Comment by Kenneth-T-Moore** [comment]
> I would suggest that the doc probably needs to tell the user how to avoid name collisions as well... I think we could tell them to do something like this to determine existing names:
> 
> ```
> from importlib.metadata import entry_points
> eps = entry_points(group='openmdao_reports')
> print([ep.name for ep in eps])
> ```

This feels like something that might be useful to put into the command line interface.

**Comment by swryan** [comment]
> > I would suggest that the doc probably needs to tell the user how to avoid name collisions as well... I think we could tell them to do something like this to determine existing names:
> > ```
> > from importlib.metadata import entry_points
> > eps = entry_points(group='openmdao_reports')
> > print([ep.name for ep in eps])
> > ```
> 
> This feels like something that might be useful to put into the command line interface.

I had that thought as well, although this is more of a developer-user thing than a user-user thing, if that makes sense ¯\_(ツ)_/¯

**Comment by Kenneth-T-Moore** [comment]
I pushed up a sentence about making sure the names are unique. Sadly, `entry_points` doesn't have a "group" argument in python 3.8, and I just get an empty list in 3.10.8, so I didn't include any way to do it.

**Review by swryan — APPROVED** [review]

**Pull request merged**
